# -*- coding: utf-8 -*-
"""Pre Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1WmNKeweEyOZFRacg_N3IdX1r6xdabO

## Import library dan Data Reviews
"""

!pip install pymongo
!pip install Sastrawi

import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt
import pymongo
from pymongo import MongoClient
import pandas as pd

import pandas as pd  # Import pustaka pandas untuk manipulasi data, terutama dalam bentuk tabel atau DataFrame
import string  # Import pustaka string untuk manipulasi string
from pymongo import MongoClient  # Import kelas MongoClient dari pustaka pymongo untuk membuat koneksi ke database MongoDB
from IPython.display import display  # Mengimpor fungsi display dari IPython.display untuk menampilkan data


# Menghubungkan ke MongoDB
client = MongoClient('YOUR_MONGODB_CONNECTION_STRING')
db = client["YOUR_DATABASE"]
collection = db["YOUR_COLLECTION"]

# Mengambil data dari koleksi MongoDB
cursor = collection.find()

# Mengonversi data ke DataFrame Pandas
df = pd.DataFrame(list(cursor))

# Menampilkan nama kolom untuk memastikan nama kolom teks asli
print(df.columns)

# Fungsi untuk membersihkan teks
def clean_text(text):
    if isinstance(text, str):
        # Mengubah teks menjadi huruf kecil
        text = text.lower()
    return text

# Ganti 'Review Text' dengan nama kolom teks asli yang benar
text_column_name = 'Review Text'

# Menambahkan kolom Clean_Text dengan teks yang telah dibersihkan
df['Clean_Text'] = df[text_column_name].apply(clean_text)

# Menampilkan beberapa baris pertama dari DataFrame dalam bentuk tabel
display(df.head(16000))

# Mengecek jumlah baris dan kolom
df.shape

# Mengecek apakah ada data yang kosong
df.isnull().sum()

# Mengecek apakah ada data yang duplikat
df.duplicated().sum()

"""## 1. Cleansing Data"""

import re

def clean_reviews(text):
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)  # Menghapus mention (kata yang dimulai dengan '@' diikuti oleh karakter alfanumerik atau underscore)
    text = re.sub(r'#\w+', '', text)  # Menghapus hashtag (kata yang dimulai dengan '#' diikuti oleh karakter alfanumerik)
    text = re.sub(r'https?://\S+', '', text)  # Menghapus URL (http atau https diikuti oleh karakter non-spasi)
    text = re.sub(r'[^A-Za-z\s]', ' ', text)   # Menghapus karakter non alfabet
    text = re.sub(r'\s+', ' ', text).strip()   # Mengganti satu atau lebih spasi dengan satu spasi dan menghapus spasi di awal/akhir teks
    text = re.sub(r'(.)\1{2,}', r'\1', text)  # Mengganti karakter yang diulang lebih dari dua kali menjadi satu karakter

    return text

# Memperbarui kolom 'Review Text' dengan membersihkan teks
df['Clean_Text'] = df['Clean_Text'].apply(clean_reviews)
df

"""## Preprocessing Data

### 2.1 Normalization
"""

import re

# Mendefinisikan sebuah kamus Python yang disimpan dalam variabel norm
norm = {
    'banget': 'sangat',
    'sukaa': 'suka',
    'bangett': 'sangat',
    'baguss': 'bagus',
    'skr': 'sekarang',
    'skg': 'sekarang',
    'sgt': 'sangat',
    'kudu': 'harus',
    'seneng': 'senang',
    'bngt': 'sangat',
    'jalanya': 'jalannya',
    'smp': 'sampai',
    'viu': 'pemandangan',
    'tourr': 'tur',
    'dri': 'dari',
    'waar biaza': 'keren',
    'tamnnya': 'taman',
    'experience': 'pengalaman',
    'iconik': 'ikonik',
    'baguus': 'bagus',
    'bersihh': 'bersih',
    'tak': 'tidak',
    'cakeep': 'bagus',
    'free': 'gratis',
    'photo': 'foto',
    'extra charge': 'biaya tambahan',
    'open trip': 'perjalanan',
    'experience': 'pengalaman',
    'first time': 'pertama kali',
    'overall': 'keseluruhan',
    'speedboat': 'perahu cepat',
    'kids': 'anak anak',
    'shuttle': 'bus',
    'cm': 'hanya',
    'kok': 'mengapa',
    'rame': 'ramai',
    'sekali': 'sangat',
    'kgn': 'rindu',
    'ngangenin': 'rindu',
    'terfavorite': 'paling favorit',
    'terfavorit': 'paling favorit',
    'goes': 'pergi',
    'pas': 'ketika',
    'terkesan': 'terasa',
    'klw': 'kalau',
    'nan': 'dan',
    'gugel': 'google',
    'yg': 'yang',
    'spt': 'seperti',
    'tp': 'tapi',
    'bgt': 'banget',
    'beneran': 'benar benar',
    'gak': 'tidak',
    'ga': 'tidak',
    'gk': 'tidak',
    'hrs': 'harus',
    'wkt': 'waktu',
    'lg': 'lagi',
    'jg': 'juga',
    'next': 'selanjutnya',
    'kmrn': 'kemarin',
    'blm': 'belum',
    'gmn': 'bagaimana',
    'dr': 'dari',
    'sm': 'sama',
    'tdk': 'tidak',
    'sdh': 'sudah',
    'bbrp': 'beberapa',
    'aja': 'saja',
    'trs': 'terus',
    'sy': 'saya',
    'kl': 'kalau',
    'km': 'kamu',
    'dgn': 'dengan',
    'jg': 'juga',
    'org': 'orang',
    'udh': 'sudah',
    'mnt': 'menit',
    'dlm': 'dalam',
    'kluarga': 'keluarga',
    'mknan': 'makanan',
    'mkn': 'makan',
    'krn': 'karena',
    'krna': 'karena',
    'tmpt': 'tempat',
    'berlibur': 'liburan',
    'stlh': 'setelah',
    'krg': 'kurang',
    'nymn': 'nyaman',
    'mrk': 'mereka',
    'smua': 'semua',
    'ntar': 'nanti',
    'kmana': 'kemana',
    'bnyk': 'banyak',
    'dpt': 'dapat',
    'ksana': 'kesana',
    'ktr': 'kantor',
    'jgn': 'jangan',
    'dgr': 'dengar',
    'udh': 'sudah',
    'asik': 'asyik',
    'cpt': 'cepat',
    'rs': 'rasa',
    'gw': 'saya',
    'ak': 'aku',
    'pdhl': 'padahal',
    'trs': 'terus',
    'mntp': 'mantap',
    'kyk': 'kayak',
    'btw': 'omong omong',
    'lho': 'loh',
    'jln': 'jalan',
    'klo': 'kalau',
    'mlm': 'malam',
    'ptg': 'petang',
    'pgi': 'pagi',
    'bgt': 'banget',
    'bkin': 'bikin',
    'lbh': 'lebih',
    'dl': 'dulu',
    'tdi': 'tadi',
    'td': 'tadi',
    'bs': 'bisa',
    'bsk': 'besok',
    'mau': 'ingin',
    'brp': 'berapa',
    'jd': 'jadi',
    'utk': 'untuk',
    'pnya': 'punya',
    'krena': 'karena',
    'cwe': 'cewek',
    'cwo': 'cowok',
    'nggak': 'tidak',
    'sdikit': 'sedikit',
    'tlg': 'tolong',
    'sblm': 'sebelum',
    'ntah': 'entah',
    'kbtulan': 'kebetulan',
    'kluar': 'keluar',
    'trakhir': 'terakhir',
    'n': 'dan',
    'sana': 'sana',
    'ksini': 'kesini',
    'ksitu': 'kesitu',
    'rmh': 'rumah',
    'msh': 'masih',
    'lgi': 'lagi',
    'yah': 'ya',
    'yg': 'yang',
    'tmpat': 'tempat',
    'mbl': 'mobil',
    'mtr': 'motor',
    'hbg': 'hubungi',
    'tau': 'tahu',
    'taunya': 'tahunya',
    'bangettt': 'banget',
    'recommended': 'direkomendasikan',
    'guide': 'pemandu',
    'telp': 'telepon',
    'spot': 'tempat',
    'rb': 'ribu',
    'dsri': 'dari',
    'sj': 'saja',
    'trs': 'terus',
    'skrg': 'sekarang',
    'cantikkk': 'cantik',
    'dll': 'dan lain lain',
    'afdol': 'mantap',
    'pulkam': 'pulang kampung',
    'disiniii': 'disini',
    'bagusss': 'bagus',
    'tempatt': 'tempat',
    'tmpny': 'tempatnya',
    'ckp': 'cukup',
    'ad': 'ada',
    'rrstony': 'restoran',
    'cpek': 'capek',
    'trllu': 'terlalu',
    'b': 'biasa',
    'y': 'iya',
    'byk': 'banyak',
    'aj': 'saja',
    'mw': 'mau',
    'htm': 'harga',
    'bangett': 'banget',
    'bersihspt': 'bersih seperti',
    'kbykn': 'kebanyakan',
    'ksni': 'kesini',
    'ttp': 'tetap',
    'sekale': 'sangat',
    'sbg': 'sebagai',
    'rp': 'rupiah',
    'jaman': 'zaman',
    'k': 'ribu',
    'd': 'di',
    'ndak': 'tidak',
    'full': 'penuh',
    'travel': 'kunjungan',
    'pm': 'setelah tengah hari',
    'am': 'sebelum tengah hari',
    'dg': 'dengan',
    'sport': 'olahraga',
    'instagramable': 'cantik',
    'worth it': 'layak',
    'worth': 'layak',
    'nice': 'bagus',
    'visit': 'kunjungan',
    'top': 'keren',
    'pol': 'sangat',
    'place': 'tempat',
    'vibe': 'suasana',
    'long weekend': 'liburan panjang',
    'asyik': 'seru',
    'asik': 'asik',
    'resto': 'restoran',
    'website': 'situs',
    'riview': 'tinjau',
    'view': 'pemandangan',
    'weekdays': 'akhir pekan',
    'work days': 'hari kerja',
    'x': 'kali',
    'beautiful': 'indah',
    'scenic': 'pemandangan',
    'amazing': 'menakjubkan',
    'breathtaking': 'mengagumkan',
    'spectacular': 'spektakuler',
    'wonderful': 'keren',
    'awesome': 'keren',
    'fantastic': 'fantastis',
    'gorgeous': 'cantik',
    'stunning': 'memukau',
    'peaceful': 'tentram',
    'relaxing': 'menenangkan',
    'enjoyable': 'menyenangkan',
    'lovely': 'menyenangkan',
    'friendly': 'ramah',
    'clean': 'bersih',
    'organized': 'teratur',
    'well-maintained': 'terawat',
    'well maintained': 'terawat',
    'safe': 'aman',
    'exciting': 'seru',
    'excited': 'seru',
    'fun': 'seru',
    'thrilling': 'menggairahkan',
    'delicious': 'lezat',
    'tasty': 'lezat',
    'authentic': 'autentik',
    'traditional': 'tradisional',
    'vibrant': 'bersemangat',
    'colorful': 'berwarna',
    'charming': 'menawan',
    'interesting': 'menarik',
    'unique': 'unik',
    'memorable': 'mengesankan',
    'unforgettable': 'tidak terlupakan',
    'refreshing': 'segar',
    'exotic': 'eksis',
    'serene': 'tenang',
    'majestic': 'megah',
    'inspiring': 'menginspirasi',
    'magical': 'ajaib',
    'magic': 'ajaib',
    'family': 'keluarga',
    'little': 'kecil',
    'm': 'meter',
    'icon': 'ikon',
    'bsa': 'bisa',
    'wonderfull': 'keren',
    'exist': 'eksis',
    'cafe': 'kafe',
    'kayak': 'seperti',
    'another magical place': 'tempat ajaib lainnya',
    'seger': 'segar',
    'idr': 'rupiah indonesia',
    'next': 'selanjutnya',
    'romantic': 'romantis',
    'attractive': 'menarik',
    'fantasy': 'fantasi',
    'fantasia': 'fantasi',
    'heavenly': 'surga',
    'paradise': 'surga',
    'wonder': 'keajaiban',
    'recommended': 'direkomendasikan',
    'guide': 'pemandu',
    'spot': 'tempat',
    'view': 'pemandangan',
    'restaurant': 'restoran',
    'hotel': 'hotel',
    'villa': 'villa',
    'beach': 'pantai',
    'coast': 'pantai',
    'sea': 'laut',
    'ocean': 'samudra',
    'sunrise': 'matahari terbit',
    'sunset': 'matahari terbenam',
    'tour': 'tur',
    'activity': 'aktivitas',
    'adventure': 'petualangan',
    'experience': 'pengalaman',
    'culture': 'budaya',
    'local': 'lokal',
    'traditional': 'tradisional',
    'festive': 'meriah',
    'festivity': 'meriah',
    'festivities': 'meriah',
    'ceremony': 'upacara',
    'ritual': 'ritual',
    'art': 'seni',
    'craft': 'kerajinan',
    'music': 'musik',
    'dance': 'tarian',
    'performance': 'pertunjukan',
    'show': 'pertunjukan',
    'event': 'acara',
    'celebration': 'perayaan',
    'festive': 'meriah',
    'festivity': 'meriah',
    'festivities': 'meriah',
    'ceremony': 'upacara',
    'ritual': 'ritual',
    'tradition': 'tradisi',
    'heritage': 'warisan',
    'history': 'sejarah',
    'historical': 'bersejarah',
    'ancient': 'kuno',
    'modern': 'modern',
    'contemporary': 'kontemporer',
    'local': 'lokal',
    'traditional': 'tradisional',
    'authentic': 'autentik',
    'cultural': 'budaya',
    'spiritual': 'spiritual',
    'religious': 'keagamaan',
    'temple': 'pura',
    'shrine': 'pemakaman',
    'mosque': 'masjid',
    'church': 'gereja',
    'cathedral': 'katedral',
    'sanctuary': 'santapan',
    'monument': 'monumen',
    'statue': 'patung',
    'sculpture': 'patung',
    'garden': 'taman',
    'park': 'taman',
    'forest': 'hutan',
    'jungle': 'hutan',
    'mountain': 'gunung',
    'hill': 'bukit',
    'volcano': 'gunung berapi',
    'lake': 'danau',
    'river': 'sungai',
    'waterfall': 'air terjun',
    'cave': 'gua',
    'spring': 'mata air',
    'pond': 'kolam',
    'pool': 'kolam renang',
    'trail': 'jalur',
    'path': 'jalan',
    'route': 'rute',
    'road': 'jalan',
    'walkway': 'jalan setapak',
    'bridge': 'jembatan',
    'gate': 'gerbang',
    'entrance': 'masuk',
    'exit': 'keluar',
    'viewpoint': 'titik pandang',
    'observatory': 'observatorium',
    'gallery': 'galeri',
    'museum': 'museum',
    'library': 'perpustakaan',
    'bookstore': 'tokobuku',
    'market': 'pasar',
    'bazaar': 'pasar',
    'shop': 'toko',
    'store': 'toko',
    'boutique': 'butik',
    'craftshop': 'toko kerajinan',
    'artgallery': 'galeri seni',
    'souvenirshop': 'toko suvenir',
    'restaurant': 'restoran',
    'cafe': 'kafetaria',
    'bar': 'bar',
    'pub': 'pub',
    'lounge': 'santai',
    'club': 'klub',
    'karaoke': 'karaoke',
    'disco': 'diskotek',
    'nightclub': 'klub malam',
    'hotel': 'hotel',
    'inn': 'penginapan',
    'resort': 'resor',
    'guesthouse': 'rumah tamu',
    'villa': 'villa',
    'one of the': 'salah satu',
    'popular': 'terkenal',
    'best': 'terbaik',
    'pool': 'kolam renang',
    'beachfront': 'tepi pantai',
    'oceanfront': 'tepi samudra',
    'seaview': 'pemandangan laut',
    'mountainview': 'pemandangan gunung',
    'lakeview': 'pemandangan danau',
    'riverside': 'tepi sungai',
    'waterfront': 'tepi air',
    'luxurious': 'mewah',
    'luxury': 'mewah',
    'affordable': 'terjangkau',
    'budget-friendly': 'ramah anggaran',
    'family-friendly': 'ramah keluarga',
    'kid-friendly': 'ramah anak-anak',
    'pet-friendly': 'ramah hewan peliharaan',
    'all-inclusive': 'semua termasuk',
    'include': 'termasuk',
    'included': 'termasuk',
    'inclusive': 'termasuk',
    'exclusive': 'eksklusif',
    'private': 'pribadi',
    'shared': 'dibagi',
    'group': 'kelompok',
    'solo': 'sendiri',
    'couple': 'pasangan',
    'romantic': 'romantis',
    'honeymoon': 'bulan madu',
    'wedding': 'pernikahan',
    'anniversary': 'perayaan',
    'birthday': 'ulang tahun',
    'party': 'pesta',
    'celebration': 'perayaan',
    'event': 'acara',
    'gathering': 'pertemuan',
    'meeting': 'pertemuan',
    'conference': 'konferensi',
    'workshop': 'bengkel',
    'retreat': 'retret',
    'escape': 'melarikan diri',
    'getaway': 'pelarian',
    'vacation': 'liburan',
    'holiday': 'hari libur',
    'staycation': 'liburan di rumah',
    'adventure': 'petualangan',
    'explore': 'menjelajah',
    'discover': 'menemukan',
    'experience': 'pengalaman',
    'journey': 'perjalanan',
    'trek': 'trekking',
    'hike': 'pendakian',
    'trail': 'jalur',
    'path': 'jalan',
    'route': 'rute',
    'activity': 'aktivitas',
    'excursion': 'ekskursi',
    'tour': 'tur',
    'sightseeing': 'melihat lihat',
    'cruise': 'pesiar',
    'boat': 'perahu',
    'yacht': 'kapal',
    'canoe': 'kano',
    'raft': 'rakit',
    'sail': 'layar',
    'surf': 'selancar',
    'snorkel': 'menyelam',
    'dive': 'menyelam',
    'swim': 'berenang',
    'sunbathe': 'berjemur',
    'relax': 'beristirahat',
    'unwind': 'bersantai',
    'rejuvenate': 'memperbaharui',
    'revitalize': 'memulihkan kembali',
    'refresh': 'menyegarkan',
    'recharge': 'mengisi kembali',
    'meditate': 'meditasi',
    'yoga': 'yoga',
    'massage': 'pijat',
    'spa': 'spa',
    'wellness': 'kesehatan',
    'well-being': 'kesejahteraan',
    'fitness': 'kebugaran',
    'exercise': 'berlatih',
    'workout': 'latihan',
    'health': 'kesehatan',
    'nutrition': 'nutrisi',
    'healthy': 'sehat',
    'organic': 'organik',
    'fresh': 'segar',
    'local': 'lokal',
    'iconic': 'ikonik',
    'delicious': 'lezat',
    'tasty': 'lezat',
    'culinary': 'kuliner',
    'gastronomic': 'gastronomi',
    'foodie': 'penggemar makanan',
    'market': 'pasar',
    'streetfood': 'makanan jalanan',
    'localfood': 'makanan lokal',
    'seafood': 'makanan laut',
    'vegetarian': 'vegetarian',
    'vegan': 'vegan',
    'gluten-free': 'bebas gluten',
    'halal': 'halal',
    'organic': 'organik',
    'farm-to-table': 'dari ladang ke meja',
    'sustainable': 'berkelanjutan',
    'eco-friendly': 'ramah lingkungan',
    'green': 'hijau',
    'nature': 'alam',
    'wildlife': 'kehidupan liar',
    'flora': 'flora',
    'fauna': 'fauna',
    'birdwatching': 'menonton burung',
    'photography': 'fotografi',
    'stargazing': 'melihat bintang',
    'camping': 'kemah',
    'picnic': 'piknik',
    'bonfire': 'api unggun',
    'barbeque': 'barbekyu',
    'fishing': 'memancing',
    'hunting': 'berburu',
    'safari': 'safari',
    'zoo': 'kebun binatang',
    'aquarium': 'akuarium',
    'botanicalgarden': 'kebun raya',
    'nationalpark': 'taman nasional',
    'marinepark': 'taman laut',
    'heritagesite': 'situs warisan',
    'landmark': 'markah tanah',
    'attraction': 'daya tarik',
    'destination': 'tujuan',
    'highlight': 'sorotan',
    'gem': 'permata',
    'hidden': 'tersembunyi',
    'gem': 'permata',
    'must-see': 'harus dilihat',
    'must-visit': 'harus dikunjungi',
    'off-the-beaten-path': 'di luar jalur',
    'famous': 'terkenal',
    'legendary': 'legendaris',
    'really': 'benar',
    'spiritual': 'spiritual',
    'religious': 'keagamaan',
    'sacred': 'sakral',
    'holy': 'suci',
    'peaceful': 'damai',
    'tranquil': 'tenang',
    'serene': 'santai',
    'relaxing': 'menyenangkan',
    'calming': 'menenangkan',
    'picturesque': 'menawan',
    'charming': 'memikat',
    'idyllic': 'idilis',
    'quaint': 'unik',
    'romantic': 'romantis',
    'bustling': 'ramai',
    'vibrant': 'bersemangat',
    'lively': 'hidup',
    'dynamic': 'dinamis',
    'energetic': 'enerjik',
    'colorful': 'penuh warna',
    'captivating': 'memukau',
    'enchanting': 'mempesona',
    'inviting': 'mengundang',
    'exhilarating': 'menggembirakan',
    'thrilling': 'seru',
    'exciting': 'mengasyikkan',
    'adventurous': 'petualangan',
    'unique': 'unik',
    'distinctive': 'khas',
    'extraordinary': 'keren',
    'awe-inspiring': 'mengagumkan',
    'jaw-dropping': 'membuat terkesima',
    'unforgettable': 'tidak terlupakan',
    'memorable': 'mengesankan',
    'spectacular': 'spektakuler',
    'stunning': 'menakjubkan',
    'remarkable': 'istimewa',
    'impressive': 'mengesankan',
    'amazing': 'menakjubkan',
    'wonderful': 'indah',
    'fantastic': 'fantastis',
    'fabulous': 'menakjubkan',
    'marvelous': 'hebat',
    'outstanding': 'istimewa',
    'superb': 'istimewa',
    'excellent': 'unggul',
    'great': 'hebat',
    'good': 'bagus',
    'pleasant': 'menyenangkan',
    'satisfying': 'memuaskan',
    'enjoyable': 'menyenangkan',
    'pleasurable': 'mengasyikkan',
    'satisfactory': 'memuaskan',
    'delightful': 'menggembirakan',
    'refreshing': 'menyegarkan',
    'relaxing': 'menyenangkan',
    'invigorating': 'menggembirakan',
    'rejuvenating': 'memperbaharui',
    'comfortable': 'nyaman',
    'cozy': 'nyaman',
    'welcoming': 'ramah',
    'friendly': 'ramah',
    'hospitality': 'keramahan',
    'accommodating': 'ramah',
    'inclusive': 'inklusif',
    'accessible': 'mudah diakses',
    'convenient': 'nyaman',
    'easy': 'mudah',
    'simple': 'sederhana',
    'effortless': 'mudah',
    'smooth': 'lancar',
    'efficient': 'efisien',
    'organized': 'terorganisir',
    'well-planned': 'direncanakan dengan baik',
    'well-designed': 'dirancang dengan baik',
    'well-maintained': 'terawat dengan baik',
    'clean': 'bersih',
    'tidy': 'rapi',
    'hygienic': 'higienis',
    'safe': 'aman',
    'secure': 'aman',
    'protected': 'terlindungi',
    'guarded': 'diawasi',
    'family-friendly': 'ramah keluarga',
    'kid-friendly': 'ramah anak anak',
    'pet-friendly': 'ramah hewan peliharaan',
    'environmentally-friendly': 'ramah lingkungan',
    'sustainable': 'berkelanjutan',
    'ethical': 'etis',
    'conscious': 'sadar',
    'responsible': 'bertanggung jawab',
    'eco-conscious': 'peduli lingkungan',
    'community-oriented': 'berorientasi pada komunitas',
    'supportive': 'mendukung',
    'helpful': 'membantu',
    'attentive': 'perhatian',
    'responsive': 'responsif',
    'courteous': 'sopan',
    'polite': 'ramah',
    'respectful': 'penuh hormat',
    'gracious': 'sopan',
    'kind': 'baik',
    'generous': 'dermawan',
    'warm': 'hangat',
    'welcoming': 'ramah',
    'inviting': 'mengundang',
    'inclusive': 'inklusif',
    'diverse': 'beragam',
    'multicultural': 'multikultural',
    'cosmopolitan': 'kosmopolitan',
    'international': 'internasional',
    'global': 'global',
    'authentic': 'asli',
    'genuine': 'asli',
    'real': 'nyata',
    'true': 'benar',
    'original': 'asli',
    'local': 'lokal',
    'traditional': 'tradisional',
    'indigenous': 'asli',
    'native': 'asli',
    'unique': 'unik',
    'distinctive': 'khas',
    'special': 'istimewa',
    'exclusive': 'eksklusif',
    'luxurious': 'mewah',
    'high-end': 'kelas atas',
    'premium': 'premium',
    'opulent': 'mewah',
    'lavish': 'mewah',
    'upscale': 'kelas atas',
    'posh': 'mewah',
    'elegant': 'elegan',
    'stylish': 'gaya',
    'chic': 'chic',
    'trendy': 'modis',
    'fashionable': 'modis',
    'hip': 'trendi',
    'modern': 'modern',
    'sleek': 'rapi'
}

def normalisasi(str_text):
    for word, replacement in norm.items():
        # Mengganti hanya kata yang berdiri sendiri
        str_text = re.sub(r'\b{}\b'.format(re.escape(word)), replacement, str_text)
    return str_text

# Menerapkan fungsi pada DataFrame
df['Clean_Text'] = df['Clean_Text'].apply(lambda x: normalisasi(x))
df

"""### 2.2 Stopword"""

!pip install Sastrawi

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary

# Mendapatkan stop words bawaan dari Sastrawi
stop_words = StopWordRemoverFactory().get_stop_words()

# Membuat ArrayDictionary baru dengan stop words yang diperbarui
new_array = ArrayDictionary(stop_words)
stop_words_remover_new = StopWordRemover(new_array)

# Fungsi untuk menghapus stop words
def stopword(str_text):
    str_text = stop_words_remover_new.remove(str_text)
    return str_text

# Menerapkan fungsi pada DataFrame
df['Clean_Text'] = df['Clean_Text'].apply(lambda x: stopword(x))
df

"""### 2.3 Tokenize"""

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

# Menggunakan nltk untuk tokenisasi
tokenized = df['Clean_Text'].apply(lambda x: word_tokenize(x))
print(tokenized)

"""### 2.4 Stemming"""

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import pandas as pd

# Fungsi untuk stemming dengan pengecualian kata tertentu
def stemming_with_exclude(text, exclude_words):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    # Menyimpan teks yang telah di-stemming
    stemmed_text = []

    # Melakukan stemming untuk setiap kalimat dalam teks
    for sentence in text:
        stemmed_sentence = []
        # Melakukan stemming untuk setiap kata dalam kalimat
        for word in sentence.split():
            # Periksa apakah kata termasuk dalam daftar kata yang dikecualikan
            if word.lower() in exclude_words:
                stemmed_sentence.append(word)
            else:
                stemmed_word = stemmer.stem(word)
                stemmed_sentence.append(stemmed_word)
        # Menggabungkan kata-kata yang telah di-stemming kembali menjadi kalimat
        stemmed_text.append(" ".join(stemmed_sentence))

    return stemmed_text

# Definisikan daftar kata yang dikecualikan dari stemming
exclude_words = {
    "bali", "ubud", "kuta", "seminyak", "nusa dua", "tanah lot", "lot", "uluwatu",
    "canggu", "sanur", "jimbaran", "lovina", "bedugul", "pura besakih",
    "ulun danu", "gunung agung", "danau batur", "taman ayun",
    "tegalalang", "pantai pandawa", "tirta empul", "garuda wisnu kencana",
    "gwk", "tegenungan", "pantai", "pura", "pulaki", "pandawa", "padang",
    "museum", "tirta", "empul", "tradisi", "kesenian", "upacara", "spa", "resort",
    "villa", "mandala", "suci", "wenara", "dewata", "legian",
    "wana", "safari", "marine", "ujung", "penataran",
    "ogoh-ogoh", "barong", "kecak", "legong", "babi guling", "ayam betutu",
    "lawar", "sate lilit", "sambal matah", "lempuyang", "tirta", "gangga",
    "besakih", "penglipuran", "petitenget", "sukawati", "beratan", "tabanan", "google"
}

# Lakukan stemming dengan pengecualian pada kolom 'Clean_Text'
df['Clean_Text'] = stemming_with_exclude(df['Clean_Text'], exclude_words)

# Cetak DataFrame yang telah diperbarui
print(df)

"""## Mengunggah data hasil pre-processing ke dalam mongodb"""

# Membuat koleksi baru dan mengunggah data hasil preprocessing ke dalamnya
new_collection_name = "YOUR_NEW_COLLECTION"
new_collection = db[new_collection_name]

# Mengunggah data hasil preprocessing ke koleksi baru
records = df.to_dict(orient='records')
new_collection.insert_many(records)

print("Koleksi baru 'clean_reviews' berhasil dibuat dan data berhasil diunggah ke MongoDB.")